// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsStepCounterApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashStepCounterApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsStepCounterApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsStepCounterApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsStepCounterApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsStepCounterApi(lhsKey, rhsKey) {
          if deepEqualsStepCounterApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsStepCounterApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashStepCounterApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashStepCounterApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashStepCounterApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashStepCounterApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashStepCounterApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashStepCounterApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Generated class from Pigeon that represents data sent in messages.
struct StepCounterNativeEvent: Hashable {
  var hardwareTotal: Int64
  var delta: Int64
  var timestampMs: Int64
  var source: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StepCounterNativeEvent? {
    let hardwareTotal = pigeonVar_list[0] as! Int64
    let delta = pigeonVar_list[1] as! Int64
    let timestampMs = pigeonVar_list[2] as! Int64
    let source = pigeonVar_list[3] as! String

    return StepCounterNativeEvent(
      hardwareTotal: hardwareTotal,
      delta: delta,
      timestampMs: timestampMs,
      source: source
    )
  }
  func toList() -> [Any?] {
    return [
      hardwareTotal,
      delta,
      timestampMs,
      source,
    ]
  }
  static func == (lhs: StepCounterNativeEvent, rhs: StepCounterNativeEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsStepCounterApi(lhs.hardwareTotal, rhs.hardwareTotal) && deepEqualsStepCounterApi(lhs.delta, rhs.delta) && deepEqualsStepCounterApi(lhs.timestampMs, rhs.timestampMs) && deepEqualsStepCounterApi(lhs.source, rhs.source)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("StepCounterNativeEvent")
    deepHashStepCounterApi(value: hardwareTotal, hasher: &hasher)
    deepHashStepCounterApi(value: delta, hasher: &hasher)
    deepHashStepCounterApi(value: timestampMs, hasher: &hasher)
    deepHashStepCounterApi(value: source, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct StepCounterNativeError: Hashable {
  var code: String
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StepCounterNativeError? {
    let code = pigeonVar_list[0] as! String
    let message = pigeonVar_list[1] as! String

    return StepCounterNativeError(
      code: code,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
    ]
  }
  static func == (lhs: StepCounterNativeError, rhs: StepCounterNativeError) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsStepCounterApi(lhs.code, rhs.code) && deepEqualsStepCounterApi(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("StepCounterNativeError")
    deepHashStepCounterApi(value: code, hasher: &hasher)
    deepHashStepCounterApi(value: message, hasher: &hasher)
  }
}

private class StepCounterApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return StepCounterNativeEvent.fromList(self.readValue() as! [Any?])
    case 130:
      return StepCounterNativeError.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class StepCounterApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? StepCounterNativeEvent {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? StepCounterNativeError {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class StepCounterApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return StepCounterApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return StepCounterApiPigeonCodecWriter(data: data)
  }
}

class StepCounterApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = StepCounterApiPigeonCodec(readerWriter: StepCounterApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol StepCounterHostApi {
  func startTracking() throws -> Bool
  func stopTracking() throws -> Bool
  func pauseTracking() throws -> Bool
  func resumeTracking() throws -> Bool
  func getHardwareTotal() throws -> Int64
  func isSensorAvailable() throws -> Bool
  func getPlatformSource() throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class StepCounterHostApiSetup {
  static var codec: FlutterStandardMessageCodec { StepCounterApiPigeonCodec.shared }
  /// Sets up an instance of `StepCounterHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: StepCounterHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startTrackingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.anufit.StepCounterHostApi.startTracking\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startTrackingChannel.setMessageHandler { _, reply in
        do {
          let result = try api.startTracking()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startTrackingChannel.setMessageHandler(nil)
    }
    let stopTrackingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.anufit.StepCounterHostApi.stopTracking\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopTrackingChannel.setMessageHandler { _, reply in
        do {
          let result = try api.stopTracking()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopTrackingChannel.setMessageHandler(nil)
    }
    let pauseTrackingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.anufit.StepCounterHostApi.pauseTracking\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseTrackingChannel.setMessageHandler { _, reply in
        do {
          let result = try api.pauseTracking()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseTrackingChannel.setMessageHandler(nil)
    }
    let resumeTrackingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.anufit.StepCounterHostApi.resumeTracking\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumeTrackingChannel.setMessageHandler { _, reply in
        do {
          let result = try api.resumeTracking()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resumeTrackingChannel.setMessageHandler(nil)
    }
    let getHardwareTotalChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.anufit.StepCounterHostApi.getHardwareTotal\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getHardwareTotalChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getHardwareTotal()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getHardwareTotalChannel.setMessageHandler(nil)
    }
    let isSensorAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.anufit.StepCounterHostApi.isSensorAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSensorAvailableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isSensorAvailable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isSensorAvailableChannel.setMessageHandler(nil)
    }
    let getPlatformSourceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.anufit.StepCounterHostApi.getPlatformSource\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPlatformSourceChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPlatformSource()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPlatformSourceChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol StepCounterFlutterApiProtocol {
  func onStepEvent(event eventArg: StepCounterNativeEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onStepError(error errorArg: StepCounterNativeError, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class StepCounterFlutterApi: StepCounterFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: StepCounterApiPigeonCodec {
    return StepCounterApiPigeonCodec.shared
  }
  func onStepEvent(event eventArg: StepCounterNativeEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.anufit.StepCounterFlutterApi.onStepEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onStepError(error errorArg: StepCounterNativeError, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.anufit.StepCounterFlutterApi.onStepError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
